import { useEffect, useState } from 'react'
import { Button, Card, EmptyState, ListRow, Modal, RemoteView, SectionHeader } from '../../kit'
import { displayDate } from './logic'
import { useEmailStore } from './store'
import type { EmailRead } from './types'

interface ComposeFields extends Record<string,string> { to:string;cc:string;bcc:string;subject:string;body:string;in_reply_to:string;references:string }
const blank:ComposeFields={to:'',cc:'',bcc:'',subject:'',body:'',in_reply_to:'',references:''}

export function EmailTab() {
  const store=useEmailStore(),[query,setQuery]=useState(''),[compose,setCompose]=useState(false),[fields,setFields]=useState<ComposeFields>(blank),[mobilePane,setMobilePane]=useState<'folders'|'messages'|'reader'>('folders')
  useEffect(()=>{void store.load()},[])
  const openCompose=(mode:'new'|'reply'|'reply-all'|'forward'='new',mail?:EmailRead)=>{
    if(!mail){setFields(blank)}else if(mode==='forward'){setFields({...blank,subject:`Fwd: ${mail.subject.replace(/^Fwd:\s*/i,'')}`,body:`\n\n---------- Forwarded message ----------\nFrom: ${mail.from_name} <${mail.from_address}>\nDate: ${mail.date}\nSubject: ${mail.subject}\nTo: ${mail.to}\n\n${mail.snippet}`})}else setFields({...blank,to:mail.from_address,cc:mode==='reply-all'?[mail.to,mail.cc].filter(Boolean).join(', '):'',subject:`Re: ${mail.subject.replace(/^Re:\s*/i,'')}`,in_reply_to:mail.message_id,references:`${mail.references} ${mail.message_id}`.trim()})
    setCompose(true)
  }
  const submit=async(draft=false)=>{try{await store.send(fields,draft);setCompose(false)}catch{/* visible store error */}}
  return <main className="next-tab next-email-tab"><SectionHeader title="Email" actions={<>{mobilePane!=='folders'&&<Button variant="ghost" onClick={()=>setMobilePane(mobilePane==='reader'?'messages':'folders')}>Back</Button>}<Button variant="ghost" onClick={()=>void store.load()}>Refresh</Button><Button onClick={()=>openCompose()}>Compose</Button></>}/>
    {store.error&&<p className="next-error-detail" role="alert">{store.error}</p>}
    <RemoteView remote={store.accounts}>{(accounts)=><p className="next-email-account">{accounts.map((account)=>`${account.name} <${account.address}>`).join(' · ')}</p>}</RemoteView>
    <div className={`next-email-grid is-${mobilePane}`}><Card className="next-email-folders" title="Folders"><RemoteView remote={store.folders} onRetry={store.load}>{(data)=><>{data.error&&<p className="next-error-detail">{data.error}</p>}{data.folders.map((folder)=><ListRow key={folder} title={folder.replace('[Gmail]/','')} selected={folder===store.folder} onClick={()=>{setMobilePane('messages');void store.chooseFolder(folder)}}/>)}</>}</RemoteView></Card>
      <Card className="next-email-messages" title="Messages"><form className="next-email-search" onSubmit={(event)=>{event.preventDefault();void store.search(query)}}><input aria-label="Search mail" value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search mail…"/><Button type="submit" variant="ghost">Search</Button></form><div className="next-email-filters"><Button variant={store.filter==='all'?'primary':'ghost'} onClick={()=>void store.setFilter('all')}>All</Button><Button variant={store.filter==='unread'?'primary':'ghost'} onClick={()=>void store.setFilter('unread')}>Unread</Button></div><RemoteView remote={store.messages} onRetry={store.load} empty={<EmptyState title="No messages"/>} isEmpty={(data)=>data.emails.length===0}>{(data)=><>{data.error&&<p className="next-error-detail">{data.error}</p>}{data.emails.map((mail)=>{const urgency=store.urgency.status==='ready'?store.urgency.data.per_uid[mail.uid]:undefined;return <ListRow key={mail.uid} title={<span style={{fontWeight:mail.is_read?400:700}}>{mail.has_attachments?'📎 ':''}{mail.subject}</span>} meta={`${mail.from_name} · ${displayDate(mail.date)}${urgency?` · ${urgency}`:''}`} selected={mail.uid===store.selectedUid} onClick={()=>{setMobilePane('reader');void store.read(mail.uid)}}/>})}</>}</RemoteView><div className="next-email-pages"><Button variant="ghost" disabled={store.offset===0} onClick={()=>void store.page(-1)}>Newer</Button><span>{store.offset+1}–{store.offset+50}</span><Button variant="ghost" disabled={store.messages.status==='ready'&&store.messages.data.emails.length<50} onClick={()=>void store.page(1)}>Older</Button></div></Card>
      <Card className="next-email-reader" title="Reader"><RemoteView remote={store.reader} empty={<EmptyState title="Choose a message"/>}>{(mail)=><><h3>{mail.subject}</h3><p>{mail.from_name} &lt;{mail.from_address}&gt;</p><p className="next-email-meta">To: {mail.to}{mail.cc&&<> · CC: {mail.cc}</>}</p>{mail.calendar&&<section className="next-email-invite"><strong>{mail.calendar.summary||'Calendar invitation'}</strong><p>{String(mail.calendar.start||'')} {mail.calendar.location?`· ${mail.calendar.location}`:''}</p><Button disabled={store.pending===mail.uid} onClick={()=>void store.rsvp(mail.uid,'accepted')}>Yes</Button><Button variant="ghost" disabled={store.pending===mail.uid} onClick={()=>void store.rsvp(mail.uid,'tentative')}>Maybe</Button><Button variant="danger" disabled={store.pending===mail.uid} onClick={()=>void store.rsvp(mail.uid,'declined')}>No</Button></section>}<iframe title="Email body" sandbox="" srcDoc={mail.body_html}/>{mail.attachments.length>0&&<div className="next-email-attachments">{mail.attachments.map((attachment)=><a key={attachment.index} className="btn btn-ghost" href={`/api/email/attachment/${encodeURIComponent(mail.uid)}/${attachment.index}?folder=${encodeURIComponent(store.folder)}`} target="_blank" rel="noreferrer">📎 {attachment.filename} · {Math.ceil(attachment.size/1024)} KB</a>)}</div>}<div className="next-email-reader-actions"><Button onClick={()=>openCompose('reply',mail)}>Reply</Button><Button variant="ghost" onClick={()=>openCompose('reply-all',mail)}>Reply all</Button><Button variant="ghost" onClick={()=>openCompose('forward',mail)}>Forward</Button><Button variant="ghost" onClick={()=>void store.summarize()}>Summarize</Button><Button variant="ghost" onClick={()=>void store.aiReply()}>AI reply</Button><Button variant="ghost" disabled={store.pending===mail.uid} onClick={()=>void store.mutate(mail.uid,mail.is_read?'mark-unread':'mark-read')}>{mail.is_read?'Mark unread':'Mark read'}</Button><Button variant="ghost" onClick={()=>void store.mutate(mail.uid,'archive')}>Archive</Button><select aria-label="Move message" defaultValue="" onChange={(event)=>{if(event.target.value)void store.move(mail.uid,event.target.value);event.target.value=''}}><option value="">Move…</option>{store.folders.status==='ready'&&store.folders.data.folders.filter((folder)=>folder!==store.folder).map((folder)=><option key={folder}>{folder}</option>)}</select><Button variant="danger" onClick={()=>{if(confirm('Move this email to Trash?'))void store.mutate(mail.uid,'delete')}}>Delete</Button></div><RemoteView remote={store.ai}>{(text)=><section className="next-email-ai"><pre>{text}</pre><Button variant="ghost" onClick={()=>{setFields({...blank,to:mail.from_address,subject:`Re: ${mail.subject.replace(/^Re:\s*/i,'')}`,body:text,in_reply_to:mail.message_id,references:`${mail.references} ${mail.message_id}`.trim()});setCompose(true)}}>Use as reply</Button></section>}</RemoteView></>}</RemoteView></Card></div>
    <RemoteView remote={store.scheduled}>{(items)=>items.length?<Card title="Scheduled">{items.map((item,index)=>{const id=String(item.sid??item.id??index);return <ListRow key={id} title={String(item.subject??'Scheduled email')} meta={String(item.send_at??'')} actions={<Button variant="danger" onClick={()=>void store.cancelScheduled(id)}>Cancel</Button>}/>})}</Card>:null}</RemoteView>
    <Modal open={compose} onClose={()=>setCompose(false)} title="Compose email"><div className="next-email-compose"><label>To<input autoFocus value={fields.to} onChange={(event)=>setFields({...fields,to:event.target.value})}/></label><label>CC<input value={fields.cc} onChange={(event)=>setFields({...fields,cc:event.target.value})}/></label><label>BCC<input value={fields.bcc} onChange={(event)=>setFields({...fields,bcc:event.target.value})}/></label><label>Subject<input value={fields.subject} onChange={(event)=>setFields({...fields,subject:event.target.value})}/></label><label>Message<textarea value={fields.body} onChange={(event)=>setFields({...fields,body:event.target.value})}/></label><div><Button disabled={Boolean(store.pending)||!fields.to.trim()} onClick={()=>void submit(false)}>Send</Button><Button variant="ghost" disabled={Boolean(store.pending)} onClick={()=>void submit(true)}>Save draft</Button></div></div></Modal>
  </main>
}
