"""Observer 1: the shell's own account of what it ran.

Bash can tell us a command's text, when it started, when it ended, and its exit
code — via a DEBUG trap and PROMPT_COMMAND, the mechanism VS Code's shell
integration uses. Sourcing the user's ~/.bashrc first keeps their environment
intact; installing the DEBUG trap LAST keeps the rcfile's own PROMPT_COMMAND
assignment from firing it and logging a phantom command.

What bash CANNOT tell us is the pid of a foreground child, and the 2026-08-12
spike showed the trap that fact sets:

  * For a foreground command, `$!` is empty. There is no child pid to be had.
  * For the command AFTER a background launch, `$!` still holds the BACKGROUND
    job's pid. A hook that records `$!` per command binds the later command's
    row to an unrelated process, so the row dies when that process dies.

Hence the only honest reading: a pid is this command's only when `$!` CHANGED
across the command. And when it did change, the recorded exit code is the
fork's, not the job's — shape B's envelope closed in 1.1 ms with exit 0 for an
18-second job — so `outcome_known` goes False and the observer must not treat
it as an outcome.

No subshells in the hook bodies: a fork per command would pollute the very
descendant scan this observer is paired with. EPOCHREALTIME and $! are shell
builtins, so each hook is fork-free.
"""
from __future__ import annotations

import logging
from pathlib import Path

from . import config

log = logging.getLogger(__name__)

RC_TEMPLATE = """\
# Generated by backend/shell_hook.py — honest-progress observer 1.
# Sources your rc first; every hook below is fork-free by design.
[ -f "$HOME/.bashrc" ] && . "$HOME/.bashrc"

__hp_start() {
  case "$BASH_COMMAND" in __hp_*) return ;; esac
  printf 'start\\t%s\\t%s\\t%s\\t%s\\n' "$EPOCHREALTIME" "$$" "$!" "$BASH_COMMAND" >> "$HP_LOG"
}

__hp_end() {
  local rc=$?
  printf 'end\\t%s\\t%s\\t%s\\t%s\\n' "$EPOCHREALTIME" "$$" "$!" "$rc" >> "$HP_LOG"
  return $rc
}

if [ -n "$HP_LOG" ]; then
  PROMPT_COMMAND="__hp_end${PROMPT_COMMAND:+; $PROMPT_COMMAND}"
  trap '__hp_start' DEBUG
fi
"""


def _safe(session_key: str) -> str:
    """A session key is a filesystem-unsafe string ("agent:main:web-abc")."""
    out = "".join(c for c in (session_key or "") if c.isalnum() or c in "-_")
    return out or "global"


def _dir() -> Path:
    return config.DATA_DIR / "shell_hook"


def rc_path(session_key: str) -> Path:
    return _dir() / f"{_safe(session_key)}.rc"


def log_path(session_key: str) -> Path:
    return _dir() / f"{_safe(session_key)}.log"


# Most of a hook log we will ever read at once. The DEBUG trap appends two
# lines per top-level command and nothing rotates the file, so a shell loop
# can write hundreds of thousands of lines; a cold backend process asking for
# offset 0 would otherwise read the whole thing in one blocking f.read()
# inside the event-loop thread, only to keep the tail. Matches the observer's
# own 64 KB text buffer.
TAIL_MAX_BYTES = 65536


def write_rc(session_key: str) -> Path:
    """Write (or refresh) this session's rcfile, and start its log empty.
    Raises OSError if the rc can't be written — the caller falls back to an
    unhooked shell.

    Truncating the log here is what bounds it at all: nothing else rotates or
    deletes these files, and write_rc runs once per shell spawn, so each new
    shell begins with a fresh log rather than appending to every command the
    previous ones ran. `read_new`'s `size < offset` reset already handles the
    resulting shrink correctly (the observer drops its buffered text and
    re-reads). A log we cannot truncate is not fatal — the reader is capped
    anyway — so it must not cost the session its hook."""
    _dir().mkdir(parents=True, exist_ok=True)
    path = rc_path(session_key)
    path.write_text(RC_TEMPLATE)
    try:
        log_path(session_key).write_bytes(b"")
    except OSError:
        log.warning("shell_hook: could not truncate the log for %s",
                    session_key, exc_info=True)
    return path


def read_new(path: Path, offset: int) -> tuple[str, int]:
    """Bytes appended since `offset`, and the new offset. A file shorter than
    the offset was truncated or replaced (a new shell for the same session), so
    it is re-read from the start — and a COLD read (offset 0) of a file bigger
    than TAIL_MAX_BYTES starts from its tail instead, since reading a
    multi-megabyte log to keep its last 64 KB blocks the event-loop thread for
    as long as that takes. The returned offset always equals the position just
    past the bytes actually returned, so the caller's stored cursor stays
    truthful; the first line of a tail read is usually a fragment, and `parse`
    drops any line it cannot read whole."""
    try:
        size = path.stat().st_size
    except OSError:
        return "", 0
    if size < offset:
        offset = 0
    if offset == 0 and size > TAIL_MAX_BYTES:
        offset = size - TAIL_MAX_BYTES
    if size == offset:
        return "", offset
    try:
        with path.open("rb") as f:
            f.seek(offset)
            raw = f.read()
    except OSError:
        return "", offset
    return raw.decode("utf-8", "replace"), offset + len(raw)


def _parse_line(line: str) -> dict | None:
    parts = line.split("\t", 4)
    if len(parts) != 5 or parts[0] not in ("start", "end"):
        return None
    try:
        ts = float(parts[1])
    except ValueError:
        return None
    bang = parts[3].strip()
    return {"ev": parts[0], "ts": ts, "bang": bang, "rest": parts[4]}


def parse(text: str) -> list[dict]:
    """Pair start/end lines into commands. A trailing partial line (the shell
    is appending as we read) is ignored; it arrives whole on the next pass."""
    lines = text.split("\n")
    if lines and lines[-1] != "":
        lines = lines[:-1]          # drop the partial tail
    out: list[dict] = []
    open_cmd: dict | None = None
    for line in lines:
        ev = _parse_line(line)
        if ev is None:
            continue
        if ev["ev"] == "start":
            if open_cmd is not None:
                out.append(open_cmd)        # never closed; outcome unknown
            open_cmd = {"text": ev["rest"], "start": ev["ts"], "end": None,
                        "exit_code": None, "bg_pid": None,
                        "outcome_known": False, "_bang": ev["bang"]}
            continue
        if open_cmd is None:
            continue
        try:
            exit_code = int(ev["rest"].strip())
        except ValueError:
            exit_code = None
        # The whole point of the module: a pid belongs to THIS command only if
        # $! moved. Otherwise it is the previous background job's, and claiming
        # it would bind this row to a process that has nothing to do with it.
        changed = ev["bang"] and ev["bang"] != open_cmd["_bang"]
        open_cmd["end"] = ev["ts"]
        open_cmd["exit_code"] = exit_code
        open_cmd["bg_pid"] = int(ev["bang"]) if changed else None
        # A command that backgrounded something returned as soon as the fork
        # succeeded. Its exit code says nothing about the work.
        open_cmd["outcome_known"] = exit_code is not None and not changed
        out.append(open_cmd)
        open_cmd = None
    if open_cmd is not None:
        out.append(open_cmd)
    for cmd in out:
        cmd.pop("_bang", None)
    return out
