import { useEffect, useState } from 'react'
import { Button, Card, EmptyState, Modal, RemoteView, SectionHeader } from '../../kit'
import { addDays, isoDay, monthWindow } from './logic'
import { useCalendarStore } from './store'
import type { CalendarEvent } from './types'
export function CalendarTab() {
  const store = useCalendarStore(), [quick, setQuick] = useState(''), [editing, setEditing] = useState<Partial<CalendarEvent> | null>(null)
  useEffect(() => { void store.load() }, [])
  const window = monthWindow(new Date(), store.offset)
  const save = async () => { if (!editing) return; await store.save(editing); setEditing(null) }
  return <main className="next-tab"><SectionHeader title="Calendar" actions={<><Button variant="ghost" onClick={() => void store.shift(-1)}>Previous</Button><Button variant="ghost" onClick={() => void store.load(0)}>Today</Button><Button variant="ghost" onClick={() => void store.shift(1)}>Next</Button><Button onClick={() => setEditing({ summary: '', dtstart: '', dtend: '', all_day: false })}>New event</Button></>} />
    <Card title={window.first.toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}><form onSubmit={(e) => { e.preventDefault(); void store.quick(quick) }}><input aria-label="Quick add" value={quick} onChange={(e) => setQuick(e.target.value)} placeholder="Lunch Friday at noon" /><Button type="submit">Parse</Button><Button variant="ghost" onClick={() => void store.syncNow()}>Sync</Button></form><RemoteView remote={store.sync}>{(result) => result.ok ? <small>Sync confirmed by server.</small> : null}</RemoteView></Card>
    <RemoteView remote={store.events} onRetry={store.load}>{(data) => <Card title="Month grid">{data.error && <p className="next-error">{data.error}</p>}<div className="next-calendar-grid" style={{ display: 'grid', gridTemplateColumns: 'repeat(7,minmax(0,1fr))', gap: 6 }}>{Array.from({ length: Math.round((window.gridEnd.getTime() - window.gridStart.getTime()) / 86_400_000) + 1 }, (_, index) => addDays(window.gridStart, index)).map((day) => { const key = isoDay(day); const events = data.events.filter((event) => event.dtstart.slice(0, 10) === key); return <section key={key} className="next-card" style={{ minHeight: 100, opacity: day.getMonth() === window.first.getMonth() ? 1 : .55 }}><strong>{day.getDate()}</strong>{events.map((event) => <button key={`${event.calendar}:${event.uid}`} className="btn btn-ghost" onClick={() => setEditing(event)}>{event.summary}</button>)}</section> })}</div>{data.events.length === 0 && <EmptyState title="No events in this window" />}</Card>}</RemoteView>
    <RemoteView remote={store.parsed}>{(event) => <Card title="Parsed event"><p>{event.summary} · {event.dtstart}</p><Button onClick={() => setEditing(event)}>Review & create</Button></Card>}</RemoteView>
    <Modal open={editing !== null} onClose={() => setEditing(null)} title={editing?.uid ? 'Edit event' : 'Create event'}>{editing && <><label>Title<input value={editing.summary ?? ''} onChange={(e) => setEditing({ ...editing, summary: e.target.value })} /></label><label>Starts<input value={editing.dtstart ?? ''} onChange={(e) => setEditing({ ...editing, dtstart: e.target.value })} /></label><label>Ends<input value={editing.dtend ?? ''} onChange={(e) => setEditing({ ...editing, dtend: e.target.value })} /></label><label>Location<input value={editing.location ?? ''} onChange={(e) => setEditing({ ...editing, location: e.target.value })} /></label><Button onClick={() => void save()}>Save</Button></>}</Modal>
  </main>
}
