import { useEffect, useMemo, useState } from 'react'
import { Button, Card, EmptyState, RemoteView, SectionHeader } from '../../kit'
import { useCronStore } from './store'

const when = (value?: number | null) => value ? new Date(value).toLocaleString() : '—'

export function CronTab() {
  const store = useCronStore()
  const [view, setView] = useState<'scheduled' | 'live'>('scheduled')
  const [query, setQuery] = useState('')
  const [status, setStatus] = useState('all')
  useEffect(() => { void store.load(); return store.watch() }, [])
  const cron = store.cron.status === 'ready' ? store.cron.data.jobs : []
  const jobs = store.jobs.status === 'ready' ? store.jobs.data : []
  const scheduled = useMemo(() => cron.filter(job => `${job.name} ${job.schedule} ${job.message ?? ''}`.toLowerCase().includes(query.toLowerCase()) && (status === 'all' || (status === 'enabled' ? job.enabled : !job.enabled))), [cron, query, status])
  const live = useMemo(() => jobs.filter(job => `${job.title ?? job.name ?? ''} ${job.status} ${job.command ?? ''}`.toLowerCase().includes(query.toLowerCase()) && (status === 'all' || job.status === status || (status === 'stalled' && Boolean(job.stalled)))), [jobs, query, status])
  const selectedCron = cron.find(job => job.id === store.selectedCron)
  const selectedJob = jobs.find(job => job.id === store.selectedJob)
  return <main className="next-tab next-cron-tab"><SectionHeader title="Cron & jobs" actions={<Button onClick={() => void store.load()}>Refresh</Button>} />
    {store.error && <div className="next-inline-error" role="alert">{store.error}</div>}
    <div className="next-cron-toolbar"><div><Button variant={view === 'scheduled' ? 'primary' : 'ghost'} onClick={() => { setView('scheduled'); setStatus('all'); store.clearSelection() }}>Scheduled · {cron.length}</Button><Button variant={view === 'live' ? 'primary' : 'ghost'} onClick={() => { setView('live'); setStatus('all'); store.clearSelection() }}>Live · {jobs.length}</Button></div><input aria-label="Search jobs" placeholder="Search jobs…" value={query} onChange={event => setQuery(event.target.value)} /><select aria-label="Filter jobs" value={status} onChange={event => setStatus(event.target.value)}>{view === 'scheduled' ? <><option value="all">All</option><option value="enabled">Enabled</option><option value="disabled">Disabled</option></> : <><option value="all">All</option><option value="running">Running</option><option value="stalled">Stalled</option><option value="failed">Failed</option><option value="done">Done</option></>}</select>{view === 'live' && <span className={`next-stream-status is-${store.streamStatus}`}>{store.streamStatus}</span>}</div>
    <div className={`next-cron-layout${store.selectedCron || store.selectedJob ? ' has-detail' : ''}`}><Card title={view === 'scheduled' ? `Scheduled · ${scheduled.length}` : `Live jobs · ${live.length}`}>
      {view === 'scheduled' ? <RemoteView remote={store.cron} onRetry={store.load} empty={<EmptyState title="No scheduled jobs" />} isEmpty={() => scheduled.length === 0}>{data => <div className="next-cron-list">{data.error && <div className="next-inline-error">{data.error}</div>}{scheduled.map(job => <article key={job.id} className={store.selectedCron === job.id ? 'is-selected' : ''}><button onClick={() => void store.showRuns(job.id)}><span className={`next-job-dot is-${job.enabled ? job.lastStatus || 'enabled' : 'disabled'}`} /><strong>{job.name}</strong><small>{job.schedule}</small><em>{job.enabled ? 'enabled' : 'disabled'} · last {job.lastStatus || 'never'} · {when(job.lastRunAtMs)}</em></button><div><Button variant="ghost" disabled={store.pending === job.id} onClick={() => { if (confirm(`Run “${job.name}” now?`)) void store.action(job, 'run') }}>Run now</Button><Button variant="ghost" disabled={store.pending === job.id} onClick={() => void store.action(job, job.enabled ? 'disable' : 'enable')}>{job.enabled ? 'Disable' : 'Enable'}</Button></div></article>)}</div>}</RemoteView> : <RemoteView remote={store.jobs} onRetry={store.load} empty={<EmptyState title="No live jobs" hint="Running and recently completed jobs appear here." />} isEmpty={() => live.length === 0}>{() => <div className="next-live-jobs">{live.map(job => <button key={job.id} className={`is-${job.stalled ? 'stalled' : job.status}${store.selectedJob === job.id ? ' is-selected' : ''}`} onClick={() => void store.showLog(job.id)}><span className={`next-job-dot is-${job.stalled ? 'stalled' : job.status}`} /><strong>{job.title || job.name || job.id}</strong><em>{job.stalled ? `stalled ${job.stalled}s` : job.status}</em><small>{job.detail || job.command || job.startedAt}</small>{(job.progress ?? job.pct) != null && <progress max={100} value={Number(job.progress ?? job.pct)} />}</button>)}</div>}</RemoteView>}
    </Card>
      {(selectedCron || selectedJob) && <Card title={selectedCron?.name || selectedJob?.title || selectedJob?.name || 'Job detail'} className="next-cron-detail"><Button variant="ghost" onClick={store.clearSelection}>← Close</Button>{selectedCron && <><dl><div><dt>Schedule</dt><dd>{selectedCron.schedule}</dd></div><div><dt>Next</dt><dd>{when(selectedCron.nextWakeAtMs)}</dd></div><div><dt>Last run</dt><dd>{when(selectedCron.lastRunAtMs)} · {selectedCron.lastStatus || '—'}</dd></div><div><dt>Target</dt><dd>{selectedCron.sessionTarget || '—'} · {selectedCron.agentId || 'default agent'}</dd></div></dl>{selectedCron.message && <pre>{selectedCron.message}</pre>}<RemoteView remote={store.runs}>{runs => runs.length ? <div className="next-cron-runs">{runs.map((run, index) => <article key={`${run.ts}:${index}`} className={`is-${run.status}`}><strong>{run.status}</strong><time>{when(run.ts)}</time><span>{run.durationMs != null ? `${(run.durationMs / 1000).toFixed(1)}s` : ''}{run.delivered != null ? ` · ${run.delivered ? 'delivered' : 'not delivered'}` : ''}</span><p>{run.summary || run.error || 'No summary'}</p></article>)}</div> : <EmptyState title="No run history" />}</RemoteView></>}{selectedJob && <><dl><div><dt>Status</dt><dd>{selectedJob.stalled ? `stalled ${selectedJob.stalled}s` : selectedJob.status}</dd></div><div><dt>Started</dt><dd>{selectedJob.startedAt || '—'}</dd></div><div><dt>PID</dt><dd>{selectedJob.pid || '—'}</dd></div></dl><Button variant="ghost" onClick={() => void store.showLog(selectedJob.id)}>Reload log</Button><RemoteView remote={store.log} onRetry={() => void store.showLog(selectedJob.id)}>{log => <pre className="next-job-log">{log || '(no output)'}</pre>}</RemoteView></>}</Card>}
    </div>
  </main>
}
