import { useEffect, useMemo, useState } from 'react'
import { Button, Card, EmptyState, RemoteView, SectionHeader } from '../../kit'
import { useChatStore } from '../chat/store'
import { Md } from '../chat/Message'
import { useResearchStore } from './store'

export function ResearchTab() {
  const store = useResearchStore()
  const [query, setQuery] = useState('')
  const [rounds, setRounds] = useState(2)
  const [category, setCategory] = useState('')
  const [search, setSearch] = useState('')
  useEffect(() => { void (async () => { await store.load(); const requested = sessionStorage.getItem('next:research'); if (requested) { sessionStorage.removeItem('next:research'); await useResearchStore.getState().open(requested) } })() }, [])
  const rows = useMemo(() => store.library.status === 'ready' ? store.library.data.research.filter(row => `${row.query} ${row.category ?? ''}`.toLowerCase().includes(search.toLowerCase())) : [], [search, store.library])
  const latest = store.progress.at(-1)
  const discuss = async (id: string) => { const sessionId = await store.spinoff(id); if (!sessionId) return; await useChatStore.getState().selectSession(sessionId); location.hash = '#/chat' }
  return <main className="next-tab next-research-tab"><SectionHeader title="Research" actions={<Button variant="ghost" onClick={() => void store.load()}>Refresh</Button>} />
    {store.error && <div className="next-inline-error" role="alert">{store.error}</div>}
    <Card title="Start deep research"><form className="next-research-start" onSubmit={event => { event.preventDefault(); if (query.trim()) void store.start(query.trim(), rounds, category) }}><textarea aria-label="Research query" value={query} onChange={event => setQuery(event.target.value)} placeholder="What should I investigate?" /><div><label>Rounds<select value={rounds} onChange={event => setRounds(Number(event.target.value))}><option value={1}>1 · quick</option><option value={2}>2 · balanced</option><option value={3}>3 · exhaustive</option></select></label><label>Category<input value={category} onChange={event => setCategory(event.target.value)} placeholder="Optional" /></label><Button type="submit" disabled={!query.trim() || store.pending === 'start'}>Start</Button>{store.runId && <Button variant="danger" disabled={Boolean(store.pending)} onClick={() => void store.cancel()}>Cancel</Button>}</div></form>
      {store.runId && <div className="next-research-progress" aria-live="polite"><strong>{latest?.phase ? `${latest.phase}…` : 'Starting…'}</strong><span>{latest?.round ? `Round ${latest.round}` : ''}{latest?.total_sources != null ? ` · ${latest.total_sources} sources` : ''}{latest?.total_findings != null ? ` · ${latest.total_findings} findings` : ''}</span>{latest?.title && <small>{latest.title}</small>}<progress max={6} value={Math.max(1, ['probing', 'planning', 'searching', 'reading', 'analyzing', 'writing'].indexOf(latest?.phase ?? '') + 1)} /></div>}
    </Card>
    <RemoteView remote={store.active}>{runs => runs.length ? <Card title="Active runs"><div className="next-research-runs">{runs.map(run => <button key={run.session_id} onClick={() => store.resume(run.session_id, run.query)}><strong>{run.query}</strong><span>{String(run.progress.phase ?? 'running')} · started {new Date(run.started_at * 1000).toLocaleString()}</span></button>)}</div></Card> : null}</RemoteView>
    <div className={`next-research-layout${store.selectedId ? ' has-report' : ''}`}><Card title="Report library"><input aria-label="Search research" placeholder="Search reports…" value={search} onChange={event => setSearch(event.target.value)} /><RemoteView remote={store.library} onRetry={store.load} empty={<EmptyState title="No research reports" />} isEmpty={() => rows.length === 0}>{() => <div className="next-research-list">{rows.map(row => <article key={row.id} className={store.selectedId === row.id ? 'is-selected' : ''}><button onClick={() => void store.open(row.id)}><strong>{row.query}</strong><span>{row.duration} · {row.source_count ?? 0} sources · {row.rounds ?? 0} rounds{row.category ? ` · ${row.category}` : ''}</span></button><div><a className="btn btn-ghost" href={`/api/research/report/${encodeURIComponent(row.id)}`} target="_blank" rel="noreferrer">Open</a><a className="btn btn-ghost" href={`/api/research/report/${encodeURIComponent(row.id)}/pdf`}>PDF</a><Button variant="ghost" disabled={store.pending === row.id} onClick={() => void discuss(row.id)}>Discuss</Button><Button variant="ghost" disabled={store.pending === row.id} onClick={() => void store.archive(row.id)}>Archive</Button><Button variant="danger" disabled={store.pending === row.id} onClick={() => { if (confirm('Delete this research report permanently?')) void store.remove(row.id) }}>Delete</Button></div></article>)}</div>}</RemoteView></Card>
      {store.selectedId && <Card title="Report" className="next-research-report"><div className="next-research-report-actions"><Button variant="ghost" onClick={() => useResearchStore.setState({ selectedId: null })}>← Close</Button><a className="btn btn-ghost" href={`/api/research/report/${encodeURIComponent(store.selectedId)}`} target="_blank" rel="noreferrer">Visual report</a><Button onClick={() => void discuss(store.selectedId!)}>Discuss in chat</Button></div><RemoteView remote={store.result}>{result => <><Md src={result.result} />{result.sources.length > 0 && <details><summary>Sources · {result.sources.length}</summary><ol>{result.sources.map((source, index) => <li key={index}>{typeof source === 'string' ? source : JSON.stringify(source)}</li>)}</ol></details>}</>}</RemoteView></Card>}
    </div>
  </main>
}
