import { useEffect, useMemo, useState } from 'react'
import { Button, Card, EmptyState, Modal, RemoteView, SectionHeader } from '../../kit'
import { useSkillsStore } from './store'
import type { Skill } from './types'

type Sort = 'confidence' | 'uses' | 'recent' | 'alpha'
const blank = { name: '', description: '', when_to_use: '', procedure: '', tags: '', category: 'general' }

export function SkillsTab() {
  const store = useSkillsStore()
  const [section, setSection] = useState<'skills' | 'builtin'>('skills')
  const [query, setQuery] = useState('')
  const [filter, setFilter] = useState('all')
  const [sort, setSort] = useState<Sort>('confidence')
  const [checked, setChecked] = useState<Set<string>>(new Set())
  const [creating, setCreating] = useState(false)
  const [form, setForm] = useState(blank)
  const [draft, setDraft] = useState('')
  const [skipAudited, setSkipAudited] = useState(true)
  useEffect(() => { void store.load(); return store.watchAudit() }, [])
  useEffect(() => { if (store.detail.status === 'ready') setDraft(store.detail.data.markdown) }, [store.detail])
  const installed = store.installed.status === 'ready' && Array.isArray(store.installed.data) ? store.installed.data : []
  const builtin = store.builtin.status === 'ready' && Array.isArray(store.builtin.data) ? store.builtin.data : []
  const rows = useMemo(() => installed.filter(skill => `${skill.name} ${skill.description} ${skill.when_to_use || ''} ${skill.category} ${(skill.tags || []).join(' ')}`.toLowerCase().includes(query.toLowerCase()) && (filter === 'all' || (filter === 'enabled' ? skill.enabled : filter === 'disabled' ? !skill.enabled : (skill.status || 'none') === filter))).sort((a, b) => sort === 'uses' ? (b.uses || 0) - (a.uses || 0) : sort === 'recent' ? (b.updated_at || b.created_at || 0) - (a.updated_at || a.created_at || 0) : sort === 'alpha' ? a.name.localeCompare(b.name) : (b.confidence || 0) - (a.confidence || 0) || a.name.localeCompare(b.name)), [installed, query, filter, sort])
  const builtins = builtin.filter(skill => `${skill.name} ${skill.description || ''}`.toLowerCase().includes(query.toLowerCase()))
  const selectedSkill = installed.find(skill => store.selected === skill.name)
  const workspaceSkill = selectedSkill?.source === 'openclaw-workspace'
  const audit = store.audit.status === 'ready' ? store.audit.data : null
  const auditSummary = audit?.results?.length ? Object.entries(audit.results.map(result => result.result || result.verdict?.verdict || 'checked').reduce<Record<string, number>>((counts, value) => ({ ...counts, [value]: (counts[value] || 0) + 1 }), {})).map(([key, value]) => `${value} ${key}`).join(' · ') : ''
  const toggleChecked = (name: string) => setChecked(value => { const next = new Set(value); next.has(name) ? next.delete(name) : next.add(name); return next })
  const startAudit = async () => { const names = checked.size ? [...checked] : rows.map(skill => skill.name); if (!names.length || !confirm(`Audit ${names.length} ${names.length === 1 ? 'skill' : 'skills'}? This runs background model evaluations.`)) return; await store.startAudit(names, skipAudited); setChecked(new Set()) }
  const add = async () => { if (await store.add(form)) { setCreating(false); setForm(blank) } }
  return <main className="next-tab next-skills-tab"><SectionHeader title={`Skills · ${installed.length}`} actions={<><Button variant="ghost" onClick={() => void store.load()}>Refresh</Button><Button disabled={!store.capabilities.add} onClick={() => setCreating(true)}>Add skill</Button></>} />
    {store.error && <div className="next-inline-error" role="alert">{store.error}</div>}
    {audit && audit.status !== 'none' && <div className={`next-skills-audit is-${audit.status}`}><header><strong>{audit.status === 'running' ? `Auditing ${audit.done || 0}/${audit.total || 0}${audit.current ? ` · ${audit.current}` : ''}` : `Audit ${audit.status} · ${audit.done || audit.total || 0}/${audit.total || 0}`}</strong>{audit.status === 'running' && <Button variant="ghost" disabled={store.pending === 'cancel-audit'} onClick={() => void store.cancelAudit()}>Cancel</Button>}</header><progress max={audit.total || 1} value={audit.done || 0} />{auditSummary && <span>{auditSummary}</span>}{audit.log?.length ? <pre>{audit.log.slice(-12).join('\n')}</pre> : null}</div>}
    <div className="next-skills-toolbar"><div><Button variant={section === 'skills' ? 'primary' : 'ghost'} onClick={() => { setSection('skills'); store.close() }}>Installed · {installed.length}</Button><Button variant={section === 'builtin' ? 'primary' : 'ghost'} onClick={() => { setSection('builtin'); store.close() }}>Built in · {builtin.length}</Button></div><input aria-label="Search skills" placeholder="Search skills…" value={query} onChange={event => setQuery(event.target.value)} />{section === 'skills' && <><select aria-label="Filter skills" value={filter} onChange={event => setFilter(event.target.value)}><option value="all">All</option><option value="enabled">Enabled</option><option value="disabled">Disabled</option><option value="published">Published</option><option value="draft">Draft</option></select><select aria-label="Sort skills" value={sort} onChange={event => setSort(event.target.value as Sort)}><option value="confidence">Confidence</option><option value="uses">Most used</option><option value="recent">Recent</option><option value="alpha">A–Z</option></select></>}</div>
    {section === 'skills' && <div className="next-skills-actions">{store.capabilities.audit ? <><label><input type="checkbox" checked={skipAudited} onChange={event => setSkipAudited(event.target.checked)} /> Skip already audited</label><span>{checked.size ? `${checked.size} selected` : `${rows.length} visible`}</span><Button variant="ghost" disabled={store.pending === 'audit' || audit?.status === 'running'} onClick={() => void startAudit()}>{store.pending === 'audit' ? 'Starting…' : checked.size ? 'Audit selected' : 'Audit visible'}</Button>{checked.size > 0 && <Button variant="ghost" onClick={() => setChecked(new Set())}>Clear</Button>}</> : <span>Automated skill audits are not provided by this gateway; enable/disable is live, and workspace skills can be created, edited, or deleted.</span>}</div>}
    <div className={`next-skills-layout${store.selected ? ' has-detail' : ''}`}><Card title={section === 'skills' ? `Installed · ${rows.length}` : `Built in · ${builtins.length}`}>
      {section === 'skills' ? <RemoteView remote={store.installed} onRetry={store.load} empty={<EmptyState title="No skills" />} isEmpty={() => rows.length === 0}>{() => <div className="next-skills-list">{rows.map(skill => <SkillRow key={skill.id || skill.name} skill={skill} selected={store.selected === skill.name} checked={checked.has(skill.name)} pending={store.pending === skill.name} onCheck={() => toggleChecked(skill.name)} onOpen={() => void store.open(skill.name)} onToggle={() => void store.toggle(skill)} />)}</div>}</RemoteView> : <RemoteView remote={store.builtin} onRetry={store.load} empty={<EmptyState title="No built-in capabilities" />} isEmpty={() => builtins.length === 0}>{() => <div className="next-skills-list">{builtins.map(skill => <article key={skill.name} className={store.selected === `builtin:${skill.name}` ? 'is-selected' : ''}><button className="next-skill-main" onClick={() => void store.open(skill.name, true)}><strong>{skill.name}</strong><p>{skill.description || 'Native capability instructions'}</p><span>built-in{skill.is_overridden ? ' · edited' : ''}</span></button></article>)}</div>}</RemoteView>}
    </Card>
      {store.selected && <Card title={store.detail.status === 'ready' ? store.detail.data.name : 'Skill detail'} className="next-skill-detail"><Button variant="ghost" onClick={store.close}>← Close</Button><RemoteView remote={store.detail} onRetry={() => { const value = store.selected || ''; void store.open(value.replace(/^builtin:/, ''), value.startsWith('builtin:')) }}>{detail => <><div className="next-skill-detail-meta"><span>{detail.builtin ? 'Built-in capability' : `${selectedSkill?.source || 'skill'} · ${selectedSkill?.category || 'general'}`}</span>{detail.builtin && <strong>Changes alter native tool instructions. Revert restores the shipped default.</strong>}{!detail.builtin && !workspaceSkill && <strong>This skill comes from a bundled or external source. Its instructions are read-only here; enable/disable remains live.</strong>}</div><textarea aria-label="Skill markdown" spellCheck={false} readOnly={detail.builtin ? !store.capabilities.builtin_edit : !workspaceSkill || !store.capabilities.edit_workspace} value={draft} onChange={event => setDraft(event.target.value)} /><div className="next-skill-detail-actions">{detail.builtin ? <>{store.capabilities.builtin_edit && <Button variant="danger" disabled={store.pending === detail.name || !detail.defaultText} onClick={() => { if (confirm(`Revert “${detail.name}” to its shipped instructions?`)) void store.revertBuiltin(detail.name) }}>Revert</Button>}<span />{store.capabilities.builtin_edit && <Button disabled={store.pending === detail.name || draft === detail.markdown} onClick={() => void store.saveBuiltin(detail.name, draft)}>Save instructions</Button>}</> : <>{workspaceSkill && store.capabilities.delete_workspace && <Button variant="danger" disabled={store.pending === detail.name} onClick={() => { if (confirm(`Delete skill “${detail.name}”? This removes its SKILL.md.`)) void store.remove(detail.name) }}>Delete</Button>}{store.capabilities.publish && <Button variant="ghost" disabled={store.pending === detail.name} onClick={() => selectedSkill && void store.setStatus(selectedSkill, selectedSkill.status === 'published' ? 'draft' : 'published')}>{selectedSkill?.status === 'published' ? 'Move to draft' : 'Publish'}</Button>}<span />{workspaceSkill && store.capabilities.edit_workspace && <Button disabled={store.pending === detail.name || draft === detail.markdown} onClick={() => void store.saveMarkdown(detail.name, draft)}>Save SKILL.md</Button>}</>}</div></>}</RemoteView></Card>}
    </div>
    <Modal open={creating} onClose={() => setCreating(false)} title="Add skill"><div className="next-skill-form"><label>Name<input value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} placeholder="optional-slug" /></label><label>Description<input value={form.description} onChange={event => setForm({ ...form, description: event.target.value })} /></label><label>When to use<textarea value={form.when_to_use} onChange={event => setForm({ ...form, when_to_use: event.target.value })} /></label><label>Procedure<textarea value={form.procedure} onChange={event => setForm({ ...form, procedure: event.target.value })} placeholder="One step per line" /></label><div><label>Category<input value={form.category} onChange={event => setForm({ ...form, category: event.target.value })} /></label><label>Tags<input value={form.tags} onChange={event => setForm({ ...form, tags: event.target.value })} placeholder="comma, separated" /></label></div><footer><Button variant="ghost" onClick={() => setCreating(false)}>Cancel</Button><Button disabled={!form.description.trim() || store.pending === 'add'} onClick={() => void add()}>{store.pending === 'add' ? 'Adding…' : 'Add draft'}</Button></footer></div></Modal>
  </main>
}

function SkillRow({ skill, selected, checked, pending, onCheck, onOpen, onToggle }: { skill: Skill; selected: boolean; checked: boolean; pending: boolean; onCheck(): void; onOpen(): void; onToggle(): void }) {
  return <article className={selected ? 'is-selected' : ''}><input aria-label={`Select ${skill.name}`} type="checkbox" checked={checked} onChange={onCheck} /><button className="next-skill-main" onClick={onOpen}><strong>{skill.emoji} {skill.name}</strong><p>{skill.description}</p><span>{skill.enabled ? 'enabled' : 'disabled'} · {skill.status || 'none'} · {skill.category}{skill.confidence != null ? ` · ${Math.round(skill.confidence * 100)}% confidence` : ''} · used {skill.uses || 0}</span></button><Button variant="ghost" disabled={pending} onClick={onToggle}>{skill.enabled ? 'Disable' : 'Enable'}</Button></article>
}
