import { useEffect, useState } from 'react'
import { Button, Card, EmptyState, Modal, RemoteView, SectionHeader } from '../../kit'
import { useSettingsStore } from './store'
import { usePwaStore, type PwaState } from '../../shell/pwa/store'
import type { ConnectionStatus } from './types'

const when = (value?: number) => value ? new Date(value * 1000).toLocaleString() : 'unknown'

export function SettingsTab() {
  const store = useSettingsStore()
  const pwaStore = usePwaStore()
  const [endpoint, setEndpoint] = useState('')
  const [model, setModel] = useState('')
  const [provider, setProvider] = useState('serpapi')
  const [count, setCount] = useState(5)
  const [fallback, setFallback] = useState('')
  useEffect(() => { void store.load(); void pwaStore.syncPushState() }, [])
  useEffect(() => { if (store.settings.status === 'ready') { const value = store.settings.data; setEndpoint(value.defaultChat.endpoint_id); setModel(value.defaultChat.model); setProvider(value.auth.search_provider || 'serpapi'); setCount(Number(value.auth.search_result_count || 5)); setFallback((value.auth.search_fallback_chain || []).join(', ')) } }, [store.settings])
  const selected = store.settings.status === 'ready' ? store.settings.data.mcp.find(server => server.id === store.selectedServer) : undefined
  const saveSearch = () => void store.saveSearch({ search_provider: provider, search_result_count: Math.max(1, Math.min(20, count)), search_fallback_chain: fallback.split(',').map(value => value.trim()).filter(Boolean) })
  return <main className="next-tab next-settings-tab"><SectionHeader title="Settings" actions={<Button variant="ghost" onClick={() => void store.load()}>Refresh status</Button>} />
    {store.error && <div className="next-inline-error" role="alert">{store.error}</div>}{store.result && <div className={`next-settings-result is-${store.result.kind}`} role="status">{store.result.message}</div>}
    <RemoteView remote={store.settings} onRetry={store.load}>{settings => <>
      <div className="next-settings-overview"><StatusCard title="Gateway" ok={settings.gateway.state === 'ok'} status={settings.gateway.state} detail={`${settings.gateway.sessionCount || 0} sessions · ${settings.gateway.agents?.length || 0} agents · since ${when(settings.gateway.since)}`} /><StatusCard title="Doctor" ok={settings.doctor.ok} status={settings.doctor.ok ? 'healthy' : 'attention needed'} detail={`${settings.doctor.checks?.filter(check => check.ok).length || 0}/${settings.doctor.checks?.length || 0} checks passing`} /><StatusCard title="Email" ok={Boolean(settings.email.enabled)} status={settings.email.enabled ? 'connected' : 'not configured'} detail={settings.email.address || settings.email.provider || 'Himalaya'} /><StatusCard title="Calendar" ok={Boolean(settings.calendar.enabled && settings.calendar.connected !== false)} status={settings.calendar.enabled ? 'connected' : 'not configured'} detail={settings.calendar.provider || 'Google Calendar'} /><NotificationsCard pwaStore={pwaStore} /></div>
      <div className="next-settings-grid"><Card title="Default chat"><div className="next-settings-form"><label>Provider<select aria-label="Default provider" value={endpoint} onChange={event => { setEndpoint(event.target.value); const group = settings.models.find(value => value.endpoint_id === event.target.value); if (group && !group.models.includes(model)) setModel(group.models[0] || '') }}>{settings.models.map(group => <option key={group.endpoint_id} value={group.endpoint_id} disabled={group.offline}>{group.endpoint_name}{group.offline ? ' · offline' : ''}</option>)}</select></label><label>Model<select aria-label="Default model" value={model} onChange={event => setModel(event.target.value)}>{settings.models.find(group => group.endpoint_id === endpoint)?.models.map((value, index) => <option key={value} value={value}>{settings.models.find(group => group.endpoint_id === endpoint)?.models_display?.[index] || value}</option>) ?? <option value={model}>{model}</option>}</select></label><Button disabled={!model || store.pending === 'default-chat'} onClick={() => void store.saveDefault(model, endpoint)}>{store.pending === 'default-chat' ? 'Saving…' : 'Save default'}</Button><small>Applies to new conversations; existing conversations keep their model.</small></div></Card>
        <Card title="Web search"><div className="next-settings-form"><label>Provider<select aria-label="Search provider" value={provider} onChange={event => setProvider(event.target.value)}><option value="serpapi">SerpAPI</option><option value="duckduckgo">DuckDuckGo</option><option value="brave">Brave</option><option value="tavily">Tavily</option></select></label><label>Results<input aria-label="Search result count" type="number" min={1} max={20} value={count} onChange={event => setCount(Number(event.target.value))} /></label><label>Fallback providers<input aria-label="Search fallback providers" value={fallback} onChange={event => setFallback(event.target.value)} placeholder="duckduckgo, brave" /></label><div><Button variant="ghost" disabled={store.pending === 'search-test'} onClick={() => void store.testSearch()}>{store.pending === 'search-test' ? 'Testing…' : 'Test search'}</Button><Button disabled={store.pending === 'search-save'} onClick={saveSearch}>{store.pending === 'search-save' ? 'Saving…' : 'Save search'}</Button></div></div></Card>
      </div>
      <div className="next-settings-grid"><ConnectionCard title="Email connection" value={settings.email} rows={[['IMAP', `${settings.email.imap_host || '—'}${settings.email.imap_port ? `:${settings.email.imap_port}` : ''}`], ['SMTP', `${settings.email.smtp_host || '—'}${settings.email.smtp_port ? `:${settings.email.smtp_port}` : ''}`]]} /><ConnectionCard title="Calendar connection" value={settings.calendar} rows={[['Scope', settings.calendar.scope || '—']]} /></div>
      <Card title={`MCP servers · ${settings.mcp.length}`}><div className="next-mcp-list">{settings.mcp.length ? settings.mcp.map(server => <article key={server.id} className={`is-${server.status}`}><span className="next-settings-dot" /><button onClick={() => void store.openTools(server.id)}><strong>{server.name}</strong><small>{server.id} · {server.transport || 'transport unknown'}</small><em>{server.status} · {server.tool_count} tools{server.error ? ` · ${server.error}` : ''}</em></button><Button variant="ghost" disabled={store.pending === `mcp:${server.id}`} onClick={() => void store.reconnect(server.id)}>{store.pending === `mcp:${server.id}` ? 'Probing…' : 'Reconnect'}</Button></article>) : <EmptyState title="No local MCP servers" />}</div></Card>
      <div className="next-settings-grid"><Card title="Diagnostics"><div className="next-doctor-list">{settings.doctor.checks?.map(check => <article key={check.id} className={check.ok ? 'is-ok' : 'is-error'}><span className="next-settings-dot" /><div><strong>{check.id.replaceAll('_', ' ')}</strong><p>{check.detail}</p>{check.hint && <small>{check.hint}</small>}</div></article>)}</div></Card><Card title="Install capabilities"><div className="next-capabilities">{Object.entries(settings.capabilities).map(([name, capability]) => <article key={name}><span className={`next-settings-dot ${capability.available ? 'is-ok' : 'is-off'}`} /><strong>{name}</strong><em>{capability.available ? 'available' : capability.reason || 'unavailable'}</em>{capability.hint && <small>{capability.hint}</small>}</article>)}</div></Card></div>
      <Card title="Workspace & data"><dl className="next-settings-meta"><div><dt>Agent</dt><dd>{settings.config.agent_name || '—'}</dd></div><div><dt>Workspace</dt><dd>{settings.config.workspace_root || '—'}</dd></div><div><dt>Source</dt><dd>{settings.config.source_url ? <a href={settings.config.source_url} target="_blank" rel="noreferrer">{settings.config.source_url}</a> : '—'}</dd></div></dl><a className="btn btn-ghost" href="/api/export">Download backup ZIP</a></Card>
    </>}</RemoteView>
    <Modal open={Boolean(store.selectedServer)} onClose={store.closeTools} title={selected?.name || 'MCP tools'}><div className="next-mcp-tools">{selected && <p>{selected.status} · {selected.transport}</p>}<RemoteView remote={store.tools} empty={<EmptyState title="No tools reported" />}>{tools => tools.map(tool => <article key={tool.name}><strong>{tool.name}</strong><p>{tool.description || 'No description'}</p></article>)}</RemoteView></div></Modal>
  </main>
}

function StatusCard({ title, ok, status, detail }: { title: string; ok: boolean; status: string; detail: string }) { return <Card><div className="next-status-card"><span className={`next-settings-dot ${ok ? 'is-ok' : 'is-error'}`} /><div><strong>{title}</strong><em>{status}</em><small>{detail}</small></div></div></Card> }
function ConnectionCard({ title, value, rows }: { title: string; value: ConnectionStatus; rows: Array<[string, string]> }) { return <Card title={title}><dl className="next-settings-meta"><div><dt>Status</dt><dd>{value.enabled ? 'Connected' : 'Not configured'}</dd></div><div><dt>Provider</dt><dd>{value.provider || '—'}</dd></div>{rows.map(([key, detail]) => <div key={key}><dt>{key}</dt><dd>{detail}</dd></div>)}</dl><small>Managed by the host connection configuration; secrets are never returned to this page.</small></Card> }
function NotificationsCard({ pwaStore }: { pwaStore: PwaState }) {
  const statusText = pwaStore.pushState === 'unsupported' ? 'not supported' : pwaStore.pushState === 'no-permission' ? 'permission denied' : pwaStore.pushState === 'on' ? 'enabled' : 'disabled'
  const ok = pwaStore.pushState === 'on'
  const detail = pwaStore.pushState === 'no-permission' ? 'Grant notification permission in browser settings' : pwaStore.pushState === 'unsupported' ? 'Service Worker push not available' : ''
  return <Card><div className="next-status-card"><span className={`next-settings-dot ${ok ? 'is-ok' : pwaStore.pushState === 'unsupported' ? 'is-off' : 'is-error'}`} /><div><strong>Notifications</strong><em>{statusText}</em>{detail && <small>{detail}</small>}{pwaStore.pushError && <small style={{ color: '#d32f2f' }}>{pwaStore.pushError}</small>}</div></div><div style={{ marginTop: '8px' }}>{pwaStore.pushState !== 'unsupported' && pwaStore.pushState !== 'no-permission' && <Button variant={pwaStore.pushState === 'on' ? 'primary' : 'ghost'} onClick={() => pwaStore.pushState === 'on' ? void pwaStore.disablePush() : void pwaStore.enablePush()}>{pwaStore.pushState === 'on' ? 'Disable notifications' : 'Enable notifications'}</Button>}</div></Card>
}
